# Generated by Django 5.2.7 on 2025-11-07 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AthleteData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('sport', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=100)),
                ('experience_years', models.FloatField()),
                ('heart_rate', models.FloatField()),
                ('duration_minutes', models.FloatField()),
                ('calories_burned', models.FloatField()),
                ('calculated_intensity', models.FloatField()),
                ('sleep_hours', models.FloatField(default=0.0)),
                ('steps', models.IntegerField(default=0)),
                ('fatigue_level', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown', max_length=100)),
                ('sport', models.CharField(default='Unknown', max_length=100)),
                ('team', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('heart_rate', models.FloatField()),
                ('duration_minutes', models.FloatField()),
                ('calories_burned', models.FloatField()),
                ('experience_years', models.FloatField(default=0)),
                ('calculated_intensity', models.FloatField()),
                ('risk_level', models.CharField(max_length=20)),
                ('strain_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InjuryPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(max_length=50)),
                ('predicted_probability', models.FloatField(default=0.0)),
                ('strain_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.athletedata')),
            ],
        ),
    ]
