# Generated by Django 5.2.7 on 2025-11-05 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AthleteData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('sport', models.CharField(max_length=50)),
                ('team', models.CharField(blank=True, max_length=100, null=True)),
                ('experience_years', models.IntegerField(default=0)),
                ('heart_rate', models.FloatField(default=0)),
                ('calories_burned', models.FloatField(default=0)),
                ('duration_minutes', models.FloatField(default=0)),
                ('calculated_intensity', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='InjuryPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(max_length=50)),
                ('predicted_probability', models.FloatField(default=0.0)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='tracker.athletedata')),
            ],
        ),
    ]
