# Generated by Django 5.2.7 on 2025-11-05 19:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='injuryprediction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='injuryprediction',
            name='strain_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='athletedata',
            name='calculated_intensity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='athletedata',
            name='calories_burned',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='athletedata',
            name='duration_minutes',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='athletedata',
            name='experience_years',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='athletedata',
            name='heart_rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='athletedata',
            name='team',
            field=models.CharField(default='Unknown Team', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='injuryprediction',
            name='athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.athletedata'),
        ),
        migrations.AlterField(
            model_name='injuryprediction',
            name='risk_level',
            field=models.CharField(max_length=10),
        ),
    ]
