# Generated by Django 5.2.7 on 2025-11-30 16:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athletesession',
            name='session_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
