# Generated by Django 5.2.7 on 2025-11-06 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_injuryprediction_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athlete_name', models.CharField(blank=True, max_length=100, null=True)),
                ('sport', models.CharField(blank=True, max_length=100, null=True)),
                ('team', models.CharField(blank=True, max_length=100, null=True)),
                ('heart_rate', models.FloatField()),
                ('duration_minutes', models.FloatField()),
                ('calories_burned', models.FloatField()),
                ('experience_years', models.FloatField()),
                ('calculated_intensity', models.FloatField()),
                ('risk_level', models.CharField(max_length=50)),
                ('strain_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='athletedata',
            name='sport',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='injuryprediction',
            name='risk_level',
            field=models.CharField(max_length=50),
        ),
    ]
