# Generated by Django 5.2.7 on 2025-12-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_athletesession_session_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='injuryprediction',
            name='recommendation',
            field=models.TextField(blank=True, default=''),
        ),
    ]
