# Generated by Django 5.2.7 on 2025-11-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_predictionhistory_alter_athletedata_sport_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictionhistory',
            name='athlete_name',
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='predictionhistory',
            name='experience_years',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='predictionhistory',
            name='risk_level',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='predictionhistory',
            name='sport',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='predictionhistory',
            name='team',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
