# Generated by Django 5.2.7 on 2025-11-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WearableData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('heart_rate', models.IntegerField()),
                ('fatigue_level', models.IntegerField()),
                ('sleep_hours', models.FloatField()),
                ('steps', models.IntegerField()),
            ],
        ),
    ]
